apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "app" . }}-{{ .Values.roleBinding.name }}
  labels:
    app: {{ include "app" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "app" . }}-{{.Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "app" . }}-{{ .Values.roles.name }}
