# Global configurations
# basePorts:
#   vote:
#     nodePort: 31000
#   result:
#     nodePort: 31001
# serviceOffsets:
#   result: 0
#   vote: 1

# Memory Utilization = (Used Memory) / (Total Memory) * 100%
# Memory Utilization = (4 GB) / (16 GB) * 100% = 25%

hpa:
  db:
    name: db-hpa
    min: 2
    max: 4
    metrics:
      type: memory
      target: Utilization
      average: 40
  redis:
    name: redis-hpa
    min: 2
    max: 4
    metrics:
      type: memory
      target: Utilization
      average: 50
  result:
    name: result-hpa
    min: 2
    max: 4
    metrics:
      type: cpu
      target: Utilization
      average: 50
  vote:
    name: vote-hpa
    min: 2
    max: 4
    metrics:
      type: cpu
      target: Utilization
      average: 50
  worker:
    name: db-hpa
    min: 3
    max: 5
    metrics:
      type: cpu
      target: Utilization
      average: 40

vpa:
  db:
    name: db-vpa
    metrics:
      cpu: 
        min: "100m"
        max: "1000m"
      memory: 
        min: "256Mi"
        max: "2Gi"
  redis:
    name: redis-vpa
    metrics:
      cpu: 
        min: "100m"
        max: "1000m"
      memory: 
        min: "256Mi"
        max: "2Gi"
  result:
    name: result-vpa
    metrics:
      cpu: 
        min: "100m"
        max: "1000m"
      memory: 
        min: "256Mi"
        max: "2Gi"
  vote:
    name: vote-vpa
    metrics:
      cpu: 
        min: "100m"
        max: "1000m"
      memory: 
        min: "256Mi"
        max: "2Gi"
  worker:
    name: worker-vpa
    metrics:
      cpu: 
        min: "100m"
        max: "1000m"
      memory: 
        min: "256Mi"
        max: "2Gi"

roles:
  name: all-access-role
  resources:
    - pods
    - services
    - persistentvolumes
    - deployments
  verbs:
    - get
    - list
    - watch

roleBinding:
  name: all-access-binding

volumes:
  db:
    name: db-volume
    storage: 1Gi
    accessModes: ReadWriteMany 
    pvrecalimpolicy: Retain
    path: /var/lib/postgresql/data
    storageClassName: manual
  redis:
    name: redis-volume
    storage: 1Gi
    accessModes: ReadWriteMany 
    pvrecalimpolicy: Retain
    path: /data
    storageClassName: manual

pvc:
  db:
    name: db-pvc
    accessModes: ReadWriteMany
    storage: 1Gi
    storageClassName: manual
  redis:
    name: redis-pvc
    accessModes: ReadWriteMany
    storage: 1Gi
    storageClassName: manual

serviceAccount:
  name: all-access-sa

replicas: 1
env: dev
secrets:
  name: db-secret
  type: Opaque
  db:
    user: postgres
    password: postgres

ingress:
  host: voteapp.local
  name: vote-app-ingress
  pathtype: Prefix
  vote: /vote/
  result: /result/

# Deployment configurations
deploy:
  db:
    name: db
    image: postgres:15-alpine
    port: 5432
    volumeMounts:
      mountPath: /var/lib/postgresql/data
      name: db-data
    volume:
      name: db-data

  redis:
    name: redis
    image: redis:alpine
    port: 6379
    volumeMounts:
      mountPath: /data
      name: redis-data
    volume:
      name: redis-data

  result:
    name: result
    image: michaelkedey/vote:result-app
    port: 80

  vote:
    name: vote
    image: michaelkedey/vote:vote-app
    port: 80

  worker:
    name: worker
    image: dockersamples/examplevotingapp_worker

# Service configurations
svc:
  db:
    name: db-svc
    ports:
      name: db-svc
      port: 5432
      targetPort: 5432
    type: ClusterIP

  redis:
    name: redis-svc
    ports:
      name: redis-svc
      port: 6379
      targetPort: 6379
    type: ClusterIP

  result:
    name: result-svc
    ports:
      name: result-svc
      port: 5071
      targetPort: 80
      nodePort: 31071
    type: NodePort

  vote:
    name: vote-svc
    ports:
      name: vote-svc
      port: 5070
      targetPort: 80
      nodePort: 31070
    type: NodePort

