apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app" . }}-{{ .Values.ingress.name }}
  labels:
    app: {{ include "app" . }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http: 
      paths:
      - path: {{ .Values.ingress.vote }}
        pathType: {{ .Values.ingress.pathtype }}
        backend:
          service:
            name: {{ include "app" . }}-{{ .Values.svc.vote.name }}
            port:
              number: {{ .Values.svc.vote.ports.targetPort }}
      - path: {{ .Values.ingress.result }}
        pathType: {{ .Values.ingress.pathtype }}
        backend:
          service:
            name: {{ include "app" . }}-{{ .Values.svc.result.name }}
            port:
              number: {{ .Values.svc.result.ports.targetPort }}
