apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-app-vpa  
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ny-app-deployment  
  updatePolicy:
    updateMode: Auto  
  resourcePolicy:
    containerPolicies:
    - containerName: my-app-container 
      minAllowed:
        cpu: "100m" 
        memory: "256Mi"  
      maxAllowed:
        cpu: "1000m"  
        memory: "2Gi" 
