apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.db.name }}-{{ include "app" . }}
  labels:
    app: {{ include "app" . }}
spec:
  capacity:
    storage: {{ .Values.volumes.db.storage }}
  accessModes: 
    - {{ .Values.volumes.db.accessModes}} 
  persistentVolumeReclaimPolicy: {{ .Values.volumes.db.pvreclaimpolicy}}
  storageClassName: {{ .Values.volumes.db.storageClassName}}
  hostPath:
    path: {{ .Values.volumes.db.path }}
