apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany  
  storageClassName: manual
  hostPath:
    path: "/var/lib/postgresql/data"
