apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "app" . }}
  name: {{ .Values.svc.db.name }}-{{ include "app" . }}
spec:
  type: {{ .Values.svc.db.type }}
  ports:
  - name: {{ .Values.svc.db.name }}
    port: {{ .Values.svc.db.ports.port }}
    targetPort: {{ .Values.svc.db.ports.targetPort }}
  selector:
    app: {{ .Values.deploy.db.name }}-{{ include "app" . }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "app" . }}
  name: {{ .Values.svc.redis.name }}-{{ include "app" . }}
spec:
  type: {{ .Values.svc.redis.type }}
  ports:
  - name: {{ .Values.svc.redis.name }}
    port: {{ .Values.svc.redis.ports.port }}
    targetPort: {{ .Values.svc.redis.ports.targetPort }}
  selector:
    app: {{ .Values.deploy.redis.name }}-{{ include "app" . }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "app" . }}
  name: {{ .Values.svc.result.name }}-{{ include "app" . }}
spec:
  type: {{ .Values.svc.result.type }}
  ports:
  - name: {{ .Values.svc.result.name }}
    port: {{ .Values.svc.result.ports.port }}
    targetPort: {{ .Values.svc.result.ports.targetPort }}
    nodePort: {{ .Values.svc.result.ports.nodePort }}
  selector:
    app: {{ .Values.deploy.result.name }}-{{ include "app" . }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "app" . }}
  name: {{ .Values.svc.vote.name }}-{{ include "app" . }}
spec:
  type: {{ .Values.svc.vote.type }}
  ports:
  - name: {{ .Values.svc.vote.name }}
    port: {{ .Values.svc.vote.ports.port }}
    targetPort: {{ .Values.svc.vote.ports.targetPort }}
    nodePort: {{ .Values.svc.vote.ports.nodePort }}
  selector:
    app: {{ .Values.deploy.vote.name }}-{{ include "app" . }}