apiVersion: autoscaling/v2 HorizontalPodAutoscaler 
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.hpa.db.name }}-{{ include "app" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
       roles: {{ .Values.hpa.roles.core }} 
    name: {{ .Values.deploy.db.name }}-{{ include "app" . }}
  minReplicas: {{ .Values.hpa.db.min }}
  maxReplicas: {{ .Values.hpa.db.max }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.hpa.db.metrics.type }}
      target:
        type: {{ .Values.hpa.db.metrics.target }}
        averageUtilization: {{ .Values.hpa.db.metrics.average }}

---

apiVersion: autoscaling/v2 HorizontalPodAutoscaler
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.hpa.result.name }}-{{ include "app" . }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    selector: 
      matchLabels:
        roles: {{ .Values.hpa.roles.secondary }}
    name: {{ .Values.deploy.result.name }}-{{ include "app" . }}
  minReplicas: {{ .Values.hpa.result.min }}
  maxReplicas: {{ .Values.hpa.result.max }}
  metrics:
  - type: Resource
    resource:
      name: {{ .Values.hpa.result.metrics.type }}
      target:
        type: {{ .Values.hpa.result.metrics.target }}
        averageUtilization: {{ .Values.hpa.result.metrics.average }}

