apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deploy.db.name }}-{{ include "app" . }}
  name: {{ .Values.svc.db.name }}-{{ include "app" . }}
spec:
  type: {{ .Values.svc.db.type }}
  ports:
  - name: {{ .Values.svc.db.name }}
    port: {{ .Values.svc.db.ports.port }}
    targetPort: {{ .Values.svc.db.ports.targetPort }}
  selector:
    app: {{ .Values.deploy.db.name }}-{{ include "app" . }}