apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "app" . }}
  name: {{ .Values.svc.redis.name }}-{{ include "app" . }}
spec:
  type: {{ .Values.svc.redis.type }}
  ports:
  - name: {{ .Values.svc.redis.name }}
    port: {{ .Values.svc.redis.ports.port }}
    targetPort: {{ .Values.svc.redis.ports.targetPort }}
  selector:
    app: {{ .Values.deploy.redis.name }}-{{ include "app" . }}