apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "app" . }}
  name: {{ .Values.svc.vote.name }}-{{ include "app" . }}
spec:
  type: {{ .Values.svc.vote.type }}
  ports:
  - name: {{ .Values.svc.vote.name }}
    port: {{ .Values.svc.vote.ports.port }}
    targetPort: {{ .Values.svc.vote.ports.targetPort }}
    nodePort: {{ .Values.svc.vote.ports.nodePort }}
  selector:
    app: {{ .Values.deploy.vote.name }}-{{ include "app" . }}