apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "app" . }}-{{ .Values.roles.name }}
  labels:
    app: {{ include "app" . }}
rules:
- apiGroups: [""]  # Core API group
  resources: {{.Values.roles.resources }}
  verbs: {{.Values.roles.verbs }}