apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-vote-app
spec:
  destination:
    name: ''
    namespace: argocd-vote-app
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s-specifications/argocd_vote-app
    repoURL: 'https://github.com/michaelkedey/example-voting-app.git'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true