apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}-{{ include "app" . }}
  labels:
    app: {{ include "app" . }}
type: {{ .Values.secrets.type }} 
data:
  # POSTGRES_USER: {{ .Values.secrets.db.user | b64enc }}
  # POSTGRES_PASSWORD: {{ .Values.secrets.db.password | b64enc }}
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=

 