apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volumes.redis.name }}-{{ include "app" . }}
  labels:
    app: {{ include "app" . }}
spec:
  capacity:
    storage: {{ .Values.volumes.redis.storage }}
  accessModes: 
    - {{ .Values.volumes.redis.accessModes }} 
  persistentVolumeReclaimPolicy: {{ .Values.volumes.redis.pvreclaimpolicy }}
  storageClassName: {{ .Values.volumes.redis.storageClassName }}
  hostPath:
    path: {{ .Values.volumes.redis.path }}
